import { ADMIN_GROUPS } from "../admin-groups";

/** Sidebar group order: website pages first, then site-wide utilities. */
export const ADMIN_NAV_GROUP_ORDER = [
  ADMIN_GROUPS.home,
  ADMIN_GROUPS.about,
  ADMIN_GROUPS.platform,
  ADMIN_GROUPS.solutions,
  ADMIN_GROUPS.resources,
  ADMIN_GROUPS.legal,
  ADMIN_GROUPS.site,
  ADMIN_GROUPS.media,
  ADMIN_GROUPS.system,
] as const;

/** Item order inside each group (`globals` or `collections` + slug). */
export const ADMIN_NAV_ENTITY_ORDER: Record<string, string[]> = {
  [ADMIN_GROUPS.home]: [
    "globals:home-hero",
    "globals:home-who-we-are",
    "globals:home-ecosystem-challenges",
    "collections:ecosystem-modules",
    "globals:home-ecosystem-gaps",
    "collections:ecosystem-gaps",
    "globals:home-partners",
    "collections:partners",
    "globals:home-security",
    "globals:home-news",
    "collections:news-articles",
    "globals:home-faqs",
    "globals:home-cta",
  ],
  [ADMIN_GROUPS.about]: [
    "globals:about-hero",
    "globals:about-vision",
    "globals:about-foundations",
    "globals:about-leadership",
    "collections:team-members",
    "globals:about-grants",
    "collections:grants-awards",
    "globals:about-cta",
  ],
  [ADMIN_GROUPS.platform]: [
    "globals:platform-hero",
    "globals:platform-features",
    "globals:platform-clinical-intelligence",
    "globals:platform-longitudinal-care",
    "globals:platform-infrastructure",
    "globals:platform-security",
    "globals:platform-cta",
  ],
  [ADMIN_GROUPS.solutions]: [
    "collections:solution-pages",
    "globals:public-health-hero",
    "globals:public-health-impact",
    "globals:public-health-three-tier",
    "globals:public-health-architecture",
    "globals:public-health-cta",
  ],
  [ADMIN_GROUPS.resources]: [
    "globals:resources-hero",
    "globals:resources-filter-tabs",
    "globals:resources-blogs-section",
    "collections:blog-posts",
    "globals:resources-blog-listing",
    "collections:featured-videos",
    "collections:short-videos",
    "globals:resources-deep-dives-section",
    "collections:deep-dives",
    "collections:external-articles",
    "globals:resources-newsletter",
  ],
  [ADMIN_GROUPS.legal]: ["globals:utility-pages", "collections:legal-pages"],
  [ADMIN_GROUPS.site]: ["globals:site-settings", "globals:navigation", "globals:footer"],
  [ADMIN_GROUPS.media]: ["collections:media"],
  [ADMIN_GROUPS.system]: ["collections:users"],
};
