/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    partners: Partner;
    'ecosystem-modules': EcosystemModule;
    'ecosystem-gaps': EcosystemGap;
    'team-members': TeamMember;
    'grants-awards': GrantsAward;
    'solution-pages': SolutionPage;
    'blog-posts': BlogPost;
    'featured-videos': FeaturedVideo;
    'short-videos': ShortVideo;
    'deep-dives': DeepDive;
    'external-articles': ExternalArticle;
    'legal-pages': LegalPage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'ecosystem-modules': EcosystemModulesSelect<false> | EcosystemModulesSelect<true>;
    'ecosystem-gaps': EcosystemGapsSelect<false> | EcosystemGapsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'grants-awards': GrantsAwardsSelect<false> | GrantsAwardsSelect<true>;
    'solution-pages': SolutionPagesSelect<false> | SolutionPagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'featured-videos': FeaturedVideosSelect<false> | FeaturedVideosSelect<true>;
    'short-videos': ShortVideosSelect<false> | ShortVideosSelect<true>;
    'deep-dives': DeepDivesSelect<false> | DeepDivesSelect<true>;
    'external-articles': ExternalArticlesSelect<false> | ExternalArticlesSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-hero': HomeHero;
    'home-who-we-are': HomeWhoWeAre;
    'home-ecosystem-challenges': HomeEcosystemChallenge;
    'home-ecosystem-gaps': HomeEcosystemGap;
    'home-partners': HomePartner;
    'home-security': HomeSecurity;
    'home-news': HomeNew;
    'home-faqs': HomeFaq;
    'home-cta': HomeCta;
    'about-hero': AboutHero;
    'about-vision': AboutVision;
    'about-foundations': AboutFoundation;
    'about-leadership': AboutLeadership;
    'about-grants': AboutGrant;
    'about-cta': AboutCta;
    'platform-hero': PlatformHero;
    'platform-features': PlatformFeature;
    'platform-clinical-intelligence': PlatformClinicalIntelligence;
    'platform-longitudinal-care': PlatformLongitudinalCare;
    'platform-infrastructure': PlatformInfrastructure;
    'platform-security': PlatformSecurity;
    'platform-cta': PlatformCta;
    'public-health-hero': PublicHealthHero;
    'public-health-impact': PublicHealthImpact;
    'public-health-three-tier': PublicHealthThreeTier;
    'public-health-architecture': PublicHealthArchitecture;
    'public-health-cta': PublicHealthCta;
    'resources-hero': ResourcesHero;
    'resources-filter-tabs': ResourcesFilterTab;
    'resources-videos-section': ResourcesVideosSection;
    'resources-deep-dives-section': ResourcesDeepDivesSection;
    'resources-articles-section': ResourcesArticlesSection;
    'resources-blogs-section': ResourcesBlogsSection;
    'resources-blog-listing': ResourcesBlogListing;
    'resources-newsletter': ResourcesNewsletter;
    'utility-pages': UtilityPage;
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-who-we-are': HomeWhoWeAreSelect<false> | HomeWhoWeAreSelect<true>;
    'home-ecosystem-challenges': HomeEcosystemChallengesSelect<false> | HomeEcosystemChallengesSelect<true>;
    'home-ecosystem-gaps': HomeEcosystemGapsSelect<false> | HomeEcosystemGapsSelect<true>;
    'home-partners': HomePartnersSelect<false> | HomePartnersSelect<true>;
    'home-security': HomeSecuritySelect<false> | HomeSecuritySelect<true>;
    'home-news': HomeNewsSelect<false> | HomeNewsSelect<true>;
    'home-faqs': HomeFaqsSelect<false> | HomeFaqsSelect<true>;
    'home-cta': HomeCtaSelect<false> | HomeCtaSelect<true>;
    'about-hero': AboutHeroSelect<false> | AboutHeroSelect<true>;
    'about-vision': AboutVisionSelect<false> | AboutVisionSelect<true>;
    'about-foundations': AboutFoundationsSelect<false> | AboutFoundationsSelect<true>;
    'about-leadership': AboutLeadershipSelect<false> | AboutLeadershipSelect<true>;
    'about-grants': AboutGrantsSelect<false> | AboutGrantsSelect<true>;
    'about-cta': AboutCtaSelect<false> | AboutCtaSelect<true>;
    'platform-hero': PlatformHeroSelect<false> | PlatformHeroSelect<true>;
    'platform-features': PlatformFeaturesSelect<false> | PlatformFeaturesSelect<true>;
    'platform-clinical-intelligence': PlatformClinicalIntelligenceSelect<false> | PlatformClinicalIntelligenceSelect<true>;
    'platform-longitudinal-care': PlatformLongitudinalCareSelect<false> | PlatformLongitudinalCareSelect<true>;
    'platform-infrastructure': PlatformInfrastructureSelect<false> | PlatformInfrastructureSelect<true>;
    'platform-security': PlatformSecuritySelect<false> | PlatformSecuritySelect<true>;
    'platform-cta': PlatformCtaSelect<false> | PlatformCtaSelect<true>;
    'public-health-hero': PublicHealthHeroSelect<false> | PublicHealthHeroSelect<true>;
    'public-health-impact': PublicHealthImpactSelect<false> | PublicHealthImpactSelect<true>;
    'public-health-three-tier': PublicHealthThreeTierSelect<false> | PublicHealthThreeTierSelect<true>;
    'public-health-architecture': PublicHealthArchitectureSelect<false> | PublicHealthArchitectureSelect<true>;
    'public-health-cta': PublicHealthCtaSelect<false> | PublicHealthCtaSelect<true>;
    'resources-hero': ResourcesHeroSelect<false> | ResourcesHeroSelect<true>;
    'resources-filter-tabs': ResourcesFilterTabsSelect<false> | ResourcesFilterTabsSelect<true>;
    'resources-videos-section': ResourcesVideosSectionSelect<false> | ResourcesVideosSectionSelect<true>;
    'resources-deep-dives-section': ResourcesDeepDivesSectionSelect<false> | ResourcesDeepDivesSectionSelect<true>;
    'resources-articles-section': ResourcesArticlesSectionSelect<false> | ResourcesArticlesSectionSelect<true>;
    'resources-blogs-section': ResourcesBlogsSectionSelect<false> | ResourcesBlogsSectionSelect<true>;
    'resources-blog-listing': ResourcesBlogListingSelect<false> | ResourcesBlogListingSelect<true>;
    'resources-newsletter': ResourcesNewsletterSelect<false> | ResourcesNewsletterSelect<true>;
    'utility-pages': UtilityPagesSelect<false> | UtilityPagesSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The logos in the scrolling partner row. Appears on the home page and the About page, under the “Partners” heading.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Used as the image description for screen readers.
   */
  name: string;
  /**
   * Recommended size: 400 × 120 px or similar wide logo. PNG or SVG with a transparent background. Use a descriptive file name such as partner-birac-logo.png, partner-amity-logo.svg. Stick to lowercase letters, numbers, and hyphens.
   */
  logo?: (number | null) | Media;
  /**
   * Leave this empty and use the Logo upload above. It is only used for logos already built into the site, such as /new/meity.jpg, and is ignored whenever an upload is present.
   */
  logoUrl?: string | null;
  /**
   * Lower numbers appear first. The current logos are numbered 10, 20, 30 and so on, so you can slot a new one in between by giving it a number like 25. New logos start at 1000, which puts them at the end of the strip.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every image and file used on the website. Upload here first, then pick the image from the page section that needs it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility. When uploading, use a descriptive file name (e.g. hero-bg.webp, partner-birac-logo.png).
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The cards in the “Ecosystem Challenges” section of the home page. Each card flips between a problem and a solution.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-modules".
 */
export interface EcosystemModule {
  id: number;
  title: string;
  description: string;
  problem: string;
  solution: string;
  /**
   * A path on this site such as /platform.
   */
  href: string;
  /**
   * Recommended size: 128 × 128 px or smaller. PNG or SVG with a transparent background. Use a descriptive file name such as grant-birac-icon.png, ecosystem-clinicians-icon.svg. Stick to lowercase letters, numbers, and hyphens.
   */
  icon?: (number | null) | Media;
  /**
   * Fallback static icon path
   */
  iconUrl?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The tabs in the “Ecosystem Gaps” section of the home page. Each tab shows a problem beside its solution.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-gaps".
 */
export interface EcosystemGap {
  id: number;
  tabLabel: string;
  problemTitle: string;
  problemDescription: string;
  solutionTitle: string;
  solutionDescription: string;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The people shown in the leadership carousel on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  title: string;
  about: string;
  /**
   * Full address, starting with https://
   */
  linkedinUrl?: string | null;
  /**
   * Recommended size: 400 × 400 px or larger square crop. JPG or WebP, under 200 KB. Use a descriptive file name such as arjun-gupta.jpg, dr-rohit-sadanand.webp. Stick to lowercase letters, numbers, and hyphens.
   */
  photo?: (number | null) | Media;
  /**
   * Optional fallback static path if no upload is provided
   */
  photoUrl?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The recognition timeline on the About page. Entries alternate left and right automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-awards".
 */
export interface GrantsAward {
  id: number;
  year: string;
  title: string;
  subtitle?: string | null;
  /**
   * Recommended size: 128 × 128 px or smaller. PNG or SVG with a transparent background. Use a descriptive file name such as grant-birac-icon.png, ecosystem-clinicians-icon.svg. Stick to lowercase letters, numbers, and hyphens.
   */
  icon?: (number | null) | Media;
  /**
   * Optional fallback static path if no upload is provided
   */
  iconUrl?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Two pages share this layout: Hospital / Clinician / CoE (/hospital) and Life Science / Pharma (/life-science). Open the one you want to edit — do not create new entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-pages".
 */
export interface SolutionPage {
  id: number;
  slug: 'hospital' | 'pharma';
  /**
   * The top of the page. The headline is split so part of it can be coloured.
   */
  hero: {
    eyebrow?: string | null;
    titleLine1: string;
    titleHighlight: string;
    subtitle: string;
  };
  /**
   * The expanding cards that describe the current burden.
   */
  clinicalBurden: {
    label: string;
    heading: string;
    description: string;
    cards?:
      | {
          label: string;
          badge: string;
          /**
           * Leave empty to cycle through Red, Blue, Teal and Grey in order.
           */
          badgeTheme?: ('red' | 'blue' | 'teal' | 'slate') | null;
          title: string;
          /**
           * Shown while the card is closed. Add exactly two lines — the card is hidden if there are fewer.
           */
          collapsedTitle: {
            line: string;
            id?: string | null;
          }[];
          description: string;
          /**
           * Optional. Leave empty to number the cards automatically (01, 02, 03…).
           */
          number?: string | null;
          /**
           * Optional. Filled in automatically from the card title if you leave it empty.
           */
          cardId?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The numbered walkthrough rows.
   */
  howItWorks: {
    label: string;
    heading: string;
    description: string;
    rows?:
      | {
          category: string;
          title: string;
          description: string;
          callout: string;
          /**
           * Optional. Leave empty to number the steps automatically (01, 02, 03…).
           */
          number?: string | null;
          reverse?: boolean | null;
          tinted?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The circular progress rings and their before/after lines.
   */
  measurableOutcomes: {
    label: string;
    heading: string;
    description: string;
    metrics?:
      | {
          label: string;
          /**
           * How far the circle fills, as a percentage.
           */
          maxPercent: number;
          /**
           * Leave empty to cycle through Red, Green and Blue in order.
           */
          metricTheme?: ('red' | 'green' | 'blue') | null;
          fromText: string;
          toText: string;
          positive: string;
          negative?: string | null;
          /**
           * Leave empty to show the percentage above.
           */
          centerValue?: string | null;
          hideCenterSubLabel?: boolean | null;
          /**
           * Optional. Filled in automatically from the metric name if you leave it empty.
           */
          metricId?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The last band on the page, above the footer.
   */
  cta: {
    heading: string;
    description: string;
    /**
     * Usually one or two. The first button is the more prominent one.
     */
    buttons?:
      | {
          label: string;
          /**
           * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
           */
          href: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles. They appear on the Resources page, on the /blog listing, and can be featured in the home page news section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * The last part of the link, e.g. rare-disease-policy gives /blog/rare-disease-policy. Lowercase letters, numbers and hyphens only. Changing this breaks existing links.
   */
  slug: string;
  excerpt: string;
  author: string;
  publishedAt: string;
  /**
   * Tick this to put the post in the large card on the left of the home page “Insights” section. If no post is ticked, the newest post is used. If several are ticked, the newest of those wins.
   */
  featuredOnHome?: boolean | null;
  readTime: string;
  category: string;
  /**
   * A hex colour for the category label. Genetico blue is #024385; amber is #d97706.
   */
  categoryColor: string;
  /**
   * Recommended size: 800 × 450 px (16:9). JPG, WebP, or PNG, under 250 KB. Use a descriptive file name such as blog-rare-disease-policy.webp. Stick to lowercase letters, numbers, and hyphens.
   */
  thumbnailImage?: (number | null) | Media;
  /**
   * Optional fallback: CSS gradient or static image path if no upload is provided
   */
  thumbnail?: string | null;
  /**
   * Add one paragraph per row. Drag to reorder.
   */
  content: {
    paragraph: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * The large video panel near the top of the Resources page. Only the first entry is shown, so keep one here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos".
 */
export interface FeaturedVideo {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Paste the link from YouTube's Share button, e.g. https://youtu.be/abc123. Shorts and normal videos both work.
   */
  youtubeUrl: string;
  duration?: string | null;
  articleLink?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * When this was published. The home page “Insights” section lists the four most recent resources of any type, newest first, using this date. Items with no date are listed after those that have one.
   */
  publishedAt?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The horizontal row of small video cards on the Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-videos".
 */
export interface ShortVideo {
  id: number;
  title: string;
  description?: string | null;
  category: string;
  /**
   * Paste the link from YouTube's Share button, e.g. https://youtu.be/abc123. Shorts and normal videos both work.
   */
  youtubeUrl: string;
  duration?: string | null;
  /**
   * When this was published. The home page “Insights” section lists the four most recent resources of any type, newest first, using this date. Items with no date are listed after those that have one.
   */
  publishedAt?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form video sessions on the Resources page. Each one gets a full-width panel that alternates left and right.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-dives".
 */
export interface DeepDive {
  id: number;
  title: string;
  description?: string | null;
  category: string;
  /**
   * Hex color for the category label (e.g. #d97706)
   */
  categoryColor?: string | null;
  /**
   * Paste the link from YouTube's Share button, e.g. https://youtu.be/abc123. Shorts and normal videos both work.
   */
  youtubeUrl: string;
  duration?: string | null;
  /**
   * Event or source shown on the video panel (e.g. Global Rare Disease Summit · Geneva)
   */
  sourceLabel?: string | null;
  /**
   * Optional CSS background gradient for the video panel. Leave empty to use the YouTube thumbnail.
   */
  thumbnailGradient?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Place the video on the left side. Leave unchecked to alternate automatically by sort order.
   */
  videoLeft?: boolean | null;
  /**
   * When this was published. The home page “Insights” section lists the four most recent resources of any type, newest first, using this date. Items with no date are listed after those that have one.
   */
  publishedAt?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Links out to articles published elsewhere (LinkedIn, press). Shown in the “Articles” section of the Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-articles".
 */
export interface ExternalArticle {
  id: number;
  title: string;
  /**
   * Full address, starting with https://
   */
  url: string;
  /**
   * When this was published. The home page “Insights” section lists the four most recent resources of any type, newest first, using this date. Items with no date are listed after those that have one.
   */
  publishedAt?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form legal pages such as the privacy policy. The web address comes from the “slug” field — privacy-policy becomes /privacy-policy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug: string;
  title: string;
  metaDescription?: string | null;
  lastUpdated: string;
  sections?:
    | {
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'ecosystem-modules';
        value: number | EcosystemModule;
      } | null)
    | ({
        relationTo: 'ecosystem-gaps';
        value: number | EcosystemGap;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'grants-awards';
        value: number | GrantsAward;
      } | null)
    | ({
        relationTo: 'solution-pages';
        value: number | SolutionPage;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'featured-videos';
        value: number | FeaturedVideo;
      } | null)
    | ({
        relationTo: 'short-videos';
        value: number | ShortVideo;
      } | null)
    | ({
        relationTo: 'deep-dives';
        value: number | DeepDive;
      } | null)
    | ({
        relationTo: 'external-articles';
        value: number | ExternalArticle;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-modules_select".
 */
export interface EcosystemModulesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  problem?: T;
  solution?: T;
  href?: T;
  icon?: T;
  iconUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-gaps_select".
 */
export interface EcosystemGapsSelect<T extends boolean = true> {
  tabLabel?: T;
  problemTitle?: T;
  problemDescription?: T;
  solutionTitle?: T;
  solutionDescription?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  about?: T;
  linkedinUrl?: T;
  photo?: T;
  photoUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-awards_select".
 */
export interface GrantsAwardsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  subtitle?: T;
  icon?: T;
  iconUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-pages_select".
 */
export interface SolutionPagesSelect<T extends boolean = true> {
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleHighlight?: T;
        subtitle?: T;
      };
  clinicalBurden?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              label?: T;
              badge?: T;
              badgeTheme?: T;
              title?: T;
              collapsedTitle?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              description?: T;
              number?: T;
              cardId?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        rows?:
          | T
          | {
              category?: T;
              title?: T;
              description?: T;
              callout?: T;
              number?: T;
              reverse?: T;
              tinted?: T;
              id?: T;
            };
      };
  measurableOutcomes?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        metrics?:
          | T
          | {
              label?: T;
              maxPercent?: T;
              metricTheme?: T;
              fromText?: T;
              toText?: T;
              positive?: T;
              negative?: T;
              centerValue?: T;
              hideCenterSubLabel?: T;
              metricId?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  author?: T;
  publishedAt?: T;
  featuredOnHome?: T;
  readTime?: T;
  category?: T;
  categoryColor?: T;
  thumbnailImage?: T;
  thumbnail?: T;
  content?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos_select".
 */
export interface FeaturedVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  youtubeUrl?: T;
  duration?: T;
  articleLink?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-videos_select".
 */
export interface ShortVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  youtubeUrl?: T;
  duration?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-dives_select".
 */
export interface DeepDivesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  categoryColor?: T;
  youtubeUrl?: T;
  duration?: T;
  sourceLabel?: T;
  thumbnailGradient?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  videoLeft?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-articles_select".
 */
export interface ExternalArticlesSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  metaDescription?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The full-screen slideshow at the very top of the home page. Each slide has its own background image, small label, headline and button — the site rotates through them automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  /**
   * Drag to reorder. Slides play top to bottom.
   */
  heroSlides?:
    | {
        /**
         * Not shown on the website — a short name so you can tell slides apart (e.g. hospitals, public-health).
         */
        id: string;
        eyebrow: string;
        title: string;
        cta: string;
        /**
         * A path on this site such as /platform, or a full https:// address.
         */
        href: string;
        /**
         * Recommended size: 1920 × 1080 px (16:9). WebP or JPG, ideally under 500 KB. Use a descriptive file name such as hero-bg.webp, hero-dna.jpg. Stick to lowercase letters, numbers, and hyphens.
         */
        backgroundImage?: (number | null) | Media;
        /**
         * Leave empty unless a developer asked you to use a built-in image path (e.g. /hero/hero-bg.webp).
         */
        image?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The introduction paragraphs directly below the slideshow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-who-we-are".
 */
export interface HomeWhoWeAre {
  id: number;
  eyebrow?: string | null;
  paragraphs?:
    | {
        text: string;
        /**
         * Copy an exact phrase from the paragraph above to colour it blue. It must match the paragraph letter for letter, or nothing will be highlighted.
         */
        highlights?:
          | {
              phrase: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading and description above the grid of challenge cards. The cards themselves are edited in “Ecosystem challenge cards” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-ecosystem-challenges".
 */
export interface HomeEcosystemChallenge {
  id: number;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading and description above the tabbed “gaps” panel. The tabs themselves are edited in “Ecosystem gap tabs” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-ecosystem-gaps".
 */
export interface HomeEcosystemGap {
  id: number;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading and description above the scrolling row of partner logos. The logos themselves are edited in “Partner logos” just below. This section also appears on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-partners".
 */
export interface HomePartner {
  id: number;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The dark panel beside the partner logos, with the list of trust and compliance points. This section also appears on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-security".
 */
export interface HomeSecurity {
  id: number;
  heading?: string | null;
  description?: string | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The news band near the bottom of the home page. Pick which blog posts, videos and articles to feature — everything you can choose here is created on the Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-news".
 */
export interface HomeNew {
  id: number;
  heading?: string | null;
  description?: string | null;
  ctaLabel?: string | null;
  resourcePicks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The frequently asked questions accordion near the bottom of the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-faqs".
 */
export interface HomeFaq {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the home page, above the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-cta".
 */
export interface HomeCta {
  id: number;
  heading?: string | null;
  description?: string | null;
  /**
   * Usually one or two. The first button is the more prominent one.
   */
  buttons?:
    | {
        label: string;
        /**
         * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
         */
        href: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the About page. The headline is split across two lines — see the help text on each field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero".
 */
export interface AboutHero {
  id: number;
  /**
   * Example: Building Infrastructure
   */
  titleLine1: string;
  /**
   * The plain words at the start of the second line, before the blue words. Example: For
   */
  titleLine2?: string | null;
  /**
   * The end of the second line, shown in blue. Example: Rare Disease Care
   */
  titleHighlight?: string | null;
  subtitle?: string | null;
  ctaLabel?: string | null;
  /**
   * A path on this site such as /platform, or a full https:// address.
   */
  ctaHref?: string | null;
  labels?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The large single-sentence statement directly below the hero.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-vision".
 */
export interface AboutVision {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The numbered list of foundation points below the vision statement. Numbering is added automatically in the order you list them here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-foundations".
 */
export interface AboutFoundation {
  id: number;
  items?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading and intro above the leadership carousel. The people themselves are edited in “Team members” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-leadership".
 */
export interface AboutLeadership {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  subtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading and intro above the recognition timeline. The entries themselves are edited in “Grants & awards” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-grants".
 */
export interface AboutGrant {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the About page, above the footer. (Section 6 — the partner logos and Security & Trust panel — is shared with the home page and is edited under “Home page”.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-cta".
 */
export interface AboutCta {
  id: number;
  heading?: string | null;
  description?: string | null;
  /**
   * Usually one or two. The first button is the more prominent one.
   */
  buttons?:
    | {
        label: string;
        /**
         * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
         */
        href: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the Platform page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-hero".
 */
export interface PlatformHero {
  id: number;
  title: string;
  subtitle?: string | null;
  ctaLabel?: string | null;
  /**
   * A path on this site such as /#get-in-touch, or a full https:// address.
   */
  ctaHref?: string | null;
  /**
   * Recommended size: 1600 × 900 px or wider (16:9). WebP, PNG, or JPG, under 600 KB. Use a descriptive file name such as platform-hero.webp, public-health-hero.png. Stick to lowercase letters, numbers, and hyphens.
   */
  image?: (number | null) | Media;
  /**
   * Optional fallback path (e.g. /hero/hero-bg.webp) if no upload is provided
   */
  imageUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The tabbed feature walkthrough below the hero. Each feature becomes one tab, numbered automatically in the order listed here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-features".
 */
export interface PlatformFeature {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  features?:
    | {
        title: string;
        category: string;
        subheading?: string | null;
        description: string;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Recommended size: 800 × 600 px or similar. SVG, PNG, or WebP with a transparent background if needed. Use a descriptive file name such as hpo-extraction.svg, ocr-digitization.png. Stick to lowercase letters, numbers, and hyphens.
         */
        illustrationImage?: (number | null) | Media;
        /**
         * Leave empty unless a developer asked you to use a built-in image path (e.g. /platform/hpo-extraction.svg).
         */
        illustration?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The clinical decision support section, with its grid of capability cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-clinical-intelligence".
 */
export interface PlatformClinicalIntelligence {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  capabilities?:
    | {
        title: string;
        description: string;
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The patient-journey section, laid out as side-by-side columns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-longitudinal-care".
 */
export interface PlatformLongitudinalCare {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  columns?:
    | {
        title: string;
        description: string;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The integrations and deployment section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-infrastructure".
 */
export interface PlatformInfrastructure {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  integrationsTitle?: string | null;
  integrationsDescription?: string | null;
  integrationTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  deploymentTitle?: string | null;
  deploymentDescription?: string | null;
  deploymentOptions?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The security cards near the bottom of the Platform page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-security".
 */
export interface PlatformSecurity {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  cards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the Platform page, above the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-cta".
 */
export interface PlatformCta {
  id: number;
  heading?: string | null;
  description?: string | null;
  /**
   * Usually one or two. The first button is the more prominent one.
   */
  buttons?:
    | {
        label: string;
        /**
         * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
         */
        href: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the Public Health page. The headline is split across two lines — see the help text on each field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-hero".
 */
export interface PublicHealthHero {
  id: number;
  /**
   * Example: Digital Backbone for
   */
  titleLine1: string;
  /**
   * The plain words at the start of the second line, before the teal words. Example: India's
   */
  titleLine2?: string | null;
  /**
   * The end of the second line, shown in teal. Example: rare disease ecosystem
   */
  titleHighlight?: string | null;
  subtitle?: string | null;
  /**
   * Recommended size: 1600 × 900 px or wider (16:9). WebP, PNG, or JPG, under 600 KB. Use a descriptive file name such as platform-hero.webp, public-health-hero.png. Stick to lowercase letters, numbers, and hyphens.
   */
  image?: (number | null) | Media;
  /**
   * Optional fallback path (e.g. /hero/hero-bg.webp) if no upload is provided
   */
  imageUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The numbered impact cards directly below the hero. Numbering is added automatically in the order you list the cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-impact".
 */
export interface PublicHealthImpact {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The three stacked tier panels that explain how the system works. List the tiers top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-three-tier".
 */
export interface PublicHealthThreeTier {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  tiers?:
    | {
        bannerLabel: string;
        happens?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        dataFlows?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        users?:
          | {
              role: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The connected-architecture diagram below the three-tier model.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-architecture".
 */
export interface PublicHealthArchitecture {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * The small heading that sits above the list below. Example: Data classification
   */
  classificationLabel?: string | null;
  classifications?:
    | {
        level: string;
        timeBadge?: string | null;
        title: string;
        description: string;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the Public Health page, above the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-cta".
 */
export interface PublicHealthCta {
  id: number;
  heading?: string | null;
  description?: string | null;
  /**
   * Usually one or two. The first button is the more prominent one.
   */
  buttons?:
    | {
        label: string;
        /**
         * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
         */
        href: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-hero".
 */
export interface ResourcesHero {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  /**
   * Recommended size: 1600 × 900 px or wider (16:9). WebP, PNG, or JPG, under 600 KB. Use a descriptive file name such as platform-hero.webp, public-health-hero.png. Stick to lowercase letters, numbers, and hyphens.
   */
  image?: (number | null) | Media;
  /**
   * Optional fallback path (e.g. /hero/hero-bg.webp) if no upload is provided
   */
  imageUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The row of filter buttons below the hero. “All” should stay first. The other tabs only work with these exact words: Featured, Videos, Articles, Blogs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-filter-tabs".
 */
export interface ResourcesFilterTab {
  id: number;
  filterTabs?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the horizontal row of short video cards. The videos themselves are edited in “Short videos” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-videos-section".
 */
export interface ResourcesVideosSection {
  id: number;
  heading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the long-form video sections. The videos themselves are edited in “Deep dives” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-deep-dives-section".
 */
export interface ResourcesDeepDivesSection {
  id: number;
  heading?: string | null;
  subtitle?: string | null;
  seeAllLabel?: string | null;
  seeAllHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the list of external article links. The links themselves are edited in “External articles” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-articles-section".
 */
export interface ResourcesArticlesSection {
  id: number;
  heading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the blog cards at the bottom of the Resources page. The posts themselves are edited in “Blog posts” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blogs-section".
 */
export interface ResourcesBlogsSection {
  id: number;
  heading?: string | null;
  seeAllLabel?: string | null;
  seeAllHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A separate page that lists every blog post, reached from “See all” on the Resources page. This section controls only its header — the posts come from “Blog posts”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blog-listing".
 */
export interface ResourcesBlogListing {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  backLabel?: string | null;
  backHref?: string | null;
  /**
   * Shown in the browser tab and in Google results.
   */
  title?: string | null;
  /**
   * The grey summary line under the page title in Google results.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the Resources page, above the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-newsletter".
 */
export interface ResourcesNewsletter {
  id: number;
  heading?: string | null;
  description?: string | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A placeholder page used for links that are not live yet. Nothing links to it from the main menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-pages".
 */
export interface UtilityPage {
  id: number;
  comingSoon?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    backLabel?: string | null;
    backHref?: string | null;
    /**
     * Shown in the browser tab and in Google results.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Used across the whole website: where contact form submissions go, the booking link, and the wording of the “Get in touch” form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  /**
   * The default summary shown in Google results and link previews.
   */
  siteDescription?: string | null;
  /**
   * Shown on the site. Where enquiries are sent.
   */
  contactEmail: string;
  contactEmailCc?: string | null;
  newsletterUrl?: string | null;
  featuredVideoUrl?: string | null;
  /**
   * The tabs across the top of the contact form. The chosen option is included in the email you receive.
   */
  contactRoles?:
    | {
        /**
         * Not shown on the website (e.g. clinician, investor).
         */
        id: string;
        label: string;
        description?: string | null;
      }[]
    | null;
  contactForm?: {
    intro?: string | null;
    submitLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    privacyNote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The menu bar at the top of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Shown left to right in this order.
   */
  mainNav?:
    | {
        label: string;
        /**
         * Leave empty for the Solutions dropdown.
         */
        href?: string | null;
        type?: ('link' | 'dropdown') | null;
        /**
         * Tick only if this item sits on a light background.
         */
        isDark?: boolean | null;
        id?: string | null;
      }[]
    | null;
  solutionsNav?:
    | {
        label: string;
        href: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The band at the bottom of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline: string;
  /**
   * The year is added automatically.
   */
  copyrightText?: string | null;
  sectionLabels?: {
    menuHeading?: string | null;
    solutionsHeading?: string | null;
  };
  menuLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  solutionsLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        name: string;
        href: string;
        platform: 'x' | 'linkedin' | 'youtube';
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactLabel?: string | null;
  /**
   * Leave empty to jump to the contact form on whichever page the visitor is on, falling back to the home page form on pages without one.
   */
  contactHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        id?: T;
        eyebrow?: T;
        title?: T;
        cta?: T;
        href?: T;
        backgroundImage?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-who-we-are_select".
 */
export interface HomeWhoWeAreSelect<T extends boolean = true> {
  eyebrow?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        highlights?:
          | T
          | {
              phrase?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-ecosystem-challenges_select".
 */
export interface HomeEcosystemChallengesSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-ecosystem-gaps_select".
 */
export interface HomeEcosystemGapsSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-partners_select".
 */
export interface HomePartnersSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-security_select".
 */
export interface HomeSecuritySelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-news_select".
 */
export interface HomeNewsSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  ctaLabel?: T;
  resourcePicks?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-faqs_select".
 */
export interface HomeFaqsSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-cta_select".
 */
export interface HomeCtaSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero_select".
 */
export interface AboutHeroSelect<T extends boolean = true> {
  titleLine1?: T;
  titleLine2?: T;
  titleHighlight?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaHref?: T;
  labels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-vision_select".
 */
export interface AboutVisionSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-foundations_select".
 */
export interface AboutFoundationsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-leadership_select".
 */
export interface AboutLeadershipSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-grants_select".
 */
export interface AboutGrantsSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-cta_select".
 */
export interface AboutCtaSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-hero_select".
 */
export interface PlatformHeroSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaHref?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-features_select".
 */
export interface PlatformFeaturesSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        category?: T;
        subheading?: T;
        description?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        illustrationImage?: T;
        illustration?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-clinical-intelligence_select".
 */
export interface PlatformClinicalIntelligenceSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-longitudinal-care_select".
 */
export interface PlatformLongitudinalCareSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-infrastructure_select".
 */
export interface PlatformInfrastructureSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  integrationsTitle?: T;
  integrationsDescription?: T;
  integrationTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  deploymentTitle?: T;
  deploymentDescription?: T;
  deploymentOptions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-security_select".
 */
export interface PlatformSecuritySelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-cta_select".
 */
export interface PlatformCtaSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-hero_select".
 */
export interface PublicHealthHeroSelect<T extends boolean = true> {
  titleLine1?: T;
  titleLine2?: T;
  titleHighlight?: T;
  subtitle?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-impact_select".
 */
export interface PublicHealthImpactSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-three-tier_select".
 */
export interface PublicHealthThreeTierSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  tiers?:
    | T
    | {
        bannerLabel?: T;
        happens?:
          | T
          | {
              item?: T;
              id?: T;
            };
        dataFlows?:
          | T
          | {
              item?: T;
              id?: T;
            };
        users?:
          | T
          | {
              role?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-architecture_select".
 */
export interface PublicHealthArchitectureSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  classificationLabel?: T;
  classifications?:
    | T
    | {
        level?: T;
        timeBadge?: T;
        title?: T;
        description?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-cta_select".
 */
export interface PublicHealthCtaSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-hero_select".
 */
export interface ResourcesHeroSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-filter-tabs_select".
 */
export interface ResourcesFilterTabsSelect<T extends boolean = true> {
  filterTabs?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-videos-section_select".
 */
export interface ResourcesVideosSectionSelect<T extends boolean = true> {
  heading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-deep-dives-section_select".
 */
export interface ResourcesDeepDivesSectionSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  seeAllLabel?: T;
  seeAllHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-articles-section_select".
 */
export interface ResourcesArticlesSectionSelect<T extends boolean = true> {
  heading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blogs-section_select".
 */
export interface ResourcesBlogsSectionSelect<T extends boolean = true> {
  heading?: T;
  seeAllLabel?: T;
  seeAllHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blog-listing_select".
 */
export interface ResourcesBlogListingSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  backLabel?: T;
  backHref?: T;
  title?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-newsletter_select".
 */
export interface ResourcesNewsletterSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttonLabel?: T;
  buttonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-pages_select".
 */
export interface UtilityPagesSelect<T extends boolean = true> {
  comingSoon?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        backLabel?: T;
        backHref?: T;
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  contactEmailCc?: T;
  newsletterUrl?: T;
  featuredVideoUrl?: T;
  contactRoles?:
    | T
    | {
        id?: T;
        label?: T;
        description?: T;
      };
  contactForm?:
    | T
    | {
        intro?: T;
        submitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
        privacyNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
        isDark?: T;
        id?: T;
      };
  solutionsNav?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  copyrightText?: T;
  sectionLabels?:
    | T
    | {
        menuHeading?: T;
        solutionsHeading?: T;
      };
  menuLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  solutionsLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        name?: T;
        href?: T;
        platform?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactLabel?: T;
  contactHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}