/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    'news-articles': NewsArticle;
    'team-members': TeamMember;
    partners: Partner;
    'grants-awards': GrantsAward;
    'ecosystem-modules': EcosystemModule;
    'ecosystem-gaps': EcosystemGap;
    'featured-videos': FeaturedVideo;
    'short-videos': ShortVideo;
    'external-articles': ExternalArticle;
    'solution-pages': SolutionPage;
    'legal-pages': LegalPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'news-articles': NewsArticlesSelect<false> | NewsArticlesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'grants-awards': GrantsAwardsSelect<false> | GrantsAwardsSelect<true>;
    'ecosystem-modules': EcosystemModulesSelect<false> | EcosystemModulesSelect<true>;
    'ecosystem-gaps': EcosystemGapsSelect<false> | EcosystemGapsSelect<true>;
    'featured-videos': FeaturedVideosSelect<false> | FeaturedVideosSelect<true>;
    'short-videos': ShortVideosSelect<false> | ShortVideosSelect<true>;
    'external-articles': ExternalArticlesSelect<false> | ExternalArticlesSelect<true>;
    'solution-pages': SolutionPagesSelect<false> | SolutionPagesSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'home-page': HomePage;
    'about-page': AboutPage;
    'platform-page': PlatformPage;
    'public-health-page': PublicHealthPage;
    'resources-page': ResourcesPage;
    'utility-pages': UtilityPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'platform-page': PlatformPageSelect<false> | PlatformPageSelect<true>;
    'public-health-page': PublicHealthPageSelect<false> | PublicHealthPageSelect<true>;
    'resources-page': ResourcesPageSelect<false> | ResourcesPageSelect<true>;
    'utility-pages': UtilityPagesSelect<false> | UtilityPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  slug: string;
  category: string;
  categoryColor: string;
  title: string;
  excerpt: string;
  author: string;
  publishedAt: string;
  readTime: string;
  /**
   * CSS gradient or image URL
   */
  thumbnail?: string | null;
  thumbnailImage?: (number | null) | Media;
  content: {
    paragraph: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles".
 */
export interface NewsArticle {
  id: number;
  title: string;
  excerpt?: string | null;
  tag?: string | null;
  author?: string | null;
  publishedAt?: string | null;
  readTime?: string | null;
  href?: string | null;
  featured?: boolean | null;
  image?: (number | null) | Media;
  /**
   * Fallback static image path
   */
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  title: string;
  about: string;
  linkedinUrl?: string | null;
  photo?: (number | null) | Media;
  /**
   * Fallback static image path
   */
  photoUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Fallback static logo path
   */
  logoUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-awards".
 */
export interface GrantsAward {
  id: number;
  year: string;
  title: string;
  subtitle?: string | null;
  icon?: (number | null) | Media;
  /**
   * Fallback static icon path
   */
  iconUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-modules".
 */
export interface EcosystemModule {
  id: number;
  title: string;
  description: string;
  problem: string;
  solution: string;
  href: string;
  icon?: (number | null) | Media;
  /**
   * Fallback static icon path
   */
  iconUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-gaps".
 */
export interface EcosystemGap {
  id: number;
  tabLabel: string;
  problemTitle: string;
  problemDescription: string;
  solutionTitle: string;
  solutionDescription: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos".
 */
export interface FeaturedVideo {
  id: number;
  title: string;
  description?: string | null;
  youtubeUrl: string;
  duration?: string | null;
  articleLink?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-videos".
 */
export interface ShortVideo {
  id: number;
  title: string;
  description?: string | null;
  category: string;
  youtubeUrl: string;
  duration?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-articles".
 */
export interface ExternalArticle {
  id: number;
  title: string;
  url: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-pages".
 */
export interface SolutionPage {
  id: number;
  slug: 'hospital' | 'pharma';
  hero: {
    eyebrow?: string | null;
    titleLine1: string;
    titleHighlight: string;
    subtitle: string;
  };
  clinicalBurden: {
    label: string;
    heading: string;
    description: string;
    cards?:
      | {
          id: string;
          number: string;
          label: string;
          badge: string;
          badgeDot: string;
          badgeBg: string;
          badgeText: string;
          title: string;
          collapsedTitle: {
            line: string;
            id?: string | null;
          }[];
          description: string;
        }[]
      | null;
  };
  howItWorks: {
    label: string;
    heading: string;
    description: string;
    rows?:
      | {
          number: string;
          category: string;
          title: string;
          description: string;
          callout: string;
          reverse?: boolean | null;
          tinted?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  measurableOutcomes: {
    label: string;
    heading: string;
    description: string;
    metrics?:
      | {
          id: string;
          maxPercent: number;
          label: string;
          ringTrack: string;
          ringFill: string;
          accent: string;
          fromText: string;
          toText: string;
          negative?: string | null;
          positive: string;
          positiveIconBg: string;
          centerValue?: string | null;
          hideCenterSubLabel?: boolean | null;
        }[]
      | null;
  };
  cta: {
    heading: string;
    description: string;
    buttons?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug: string;
  title: string;
  metaDescription?: string | null;
  lastUpdated: string;
  sections?:
    | {
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'news-articles';
        value: number | NewsArticle;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'grants-awards';
        value: number | GrantsAward;
      } | null)
    | ({
        relationTo: 'ecosystem-modules';
        value: number | EcosystemModule;
      } | null)
    | ({
        relationTo: 'ecosystem-gaps';
        value: number | EcosystemGap;
      } | null)
    | ({
        relationTo: 'featured-videos';
        value: number | FeaturedVideo;
      } | null)
    | ({
        relationTo: 'short-videos';
        value: number | ShortVideo;
      } | null)
    | ({
        relationTo: 'external-articles';
        value: number | ExternalArticle;
      } | null)
    | ({
        relationTo: 'solution-pages';
        value: number | SolutionPage;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  slug?: T;
  category?: T;
  categoryColor?: T;
  title?: T;
  excerpt?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  thumbnail?: T;
  thumbnailImage?: T;
  content?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles_select".
 */
export interface NewsArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  tag?: T;
  author?: T;
  publishedAt?: T;
  readTime?: T;
  href?: T;
  featured?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  about?: T;
  linkedinUrl?: T;
  photo?: T;
  photoUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-awards_select".
 */
export interface GrantsAwardsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  subtitle?: T;
  icon?: T;
  iconUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-modules_select".
 */
export interface EcosystemModulesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  problem?: T;
  solution?: T;
  href?: T;
  icon?: T;
  iconUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecosystem-gaps_select".
 */
export interface EcosystemGapsSelect<T extends boolean = true> {
  tabLabel?: T;
  problemTitle?: T;
  problemDescription?: T;
  solutionTitle?: T;
  solutionDescription?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos_select".
 */
export interface FeaturedVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  youtubeUrl?: T;
  duration?: T;
  articleLink?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-videos_select".
 */
export interface ShortVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  youtubeUrl?: T;
  duration?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-articles_select".
 */
export interface ExternalArticlesSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-pages_select".
 */
export interface SolutionPagesSelect<T extends boolean = true> {
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleHighlight?: T;
        subtitle?: T;
      };
  clinicalBurden?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              id?: T;
              number?: T;
              label?: T;
              badge?: T;
              badgeDot?: T;
              badgeBg?: T;
              badgeText?: T;
              title?: T;
              collapsedTitle?:
                | T
                | {
                    line?: T;
                    id?: T;
                  };
              description?: T;
            };
      };
  howItWorks?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        rows?:
          | T
          | {
              number?: T;
              category?: T;
              title?: T;
              description?: T;
              callout?: T;
              reverse?: T;
              tinted?: T;
              id?: T;
            };
      };
  measurableOutcomes?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        metrics?:
          | T
          | {
              id?: T;
              maxPercent?: T;
              label?: T;
              ringTrack?: T;
              ringFill?: T;
              accent?: T;
              fromText?: T;
              toText?: T;
              negative?: T;
              positive?: T;
              positiveIconBg?: T;
              centerValue?: T;
              hideCenterSubLabel?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  metaDescription?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  contactEmail: string;
  contactEmailCc?: string | null;
  calendlyUrl?: string | null;
  newsletterUrl?: string | null;
  featuredVideoUrl?: string | null;
  contactRoles?:
    | {
        id: string;
        label: string;
        description?: string | null;
      }[]
    | null;
  contactForm?: {
    intro?: string | null;
    submitLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    privacyNote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        href?: string | null;
        type?: ('link' | 'dropdown') | null;
        isDark?: boolean | null;
        id?: string | null;
      }[]
    | null;
  solutionsNav?:
    | {
        label: string;
        href: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline: string;
  copyrightText?: string | null;
  sectionLabels?: {
    menuHeading?: string | null;
    solutionsHeading?: string | null;
  };
  menuLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  solutionsLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        name: string;
        href: string;
        platform: 'x' | 'linkedin' | 'youtube';
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactLabel?: string | null;
  contactHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroSlides?:
    | {
        id: string;
        title: string;
        body: string;
        cta: string;
        href: string;
        image: string;
      }[]
    | null;
  whoWeAre?: {
    eyebrow?: string | null;
    paragraphs?:
      | {
          text: string;
          highlight?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ecosystemChallenges?: {
    heading?: string | null;
    description?: string | null;
  };
  ecosystemGaps?: {
    heading?: string | null;
    description?: string | null;
  };
  partners?: {
    heading?: string | null;
    description?: string | null;
  };
  security?: {
    heading?: string | null;
    description?: string | null;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  news?: {
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  cta?: {
    heading?: string | null;
    description?: string | null;
    buttons?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    labels?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  vision?: {
    heading?: string | null;
  };
  foundations?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  leadership?: {
    eyebrow?: string | null;
    heading?: string | null;
    subtitle?: string | null;
  };
  grants?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
  };
  cta?: {
    heading?: string | null;
    description?: string | null;
    buttons?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-page".
 */
export interface PlatformPage {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    image?: string | null;
  };
  featuresSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    features?:
      | {
          category: string;
          subheading?: string | null;
          title: string;
          description: string;
          bullets?:
            | {
                item: string;
                id?: string | null;
              }[]
            | null;
          illustration?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  clinicalIntelligence?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    capabilities?:
      | {
          title: string;
          description: string;
          badge?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  longitudinalCare?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    columns?:
      | {
          title: string;
          description: string;
          bullets?:
            | {
                item: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  infrastructure?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    integrationTags?:
      | {
          tag: string;
          id?: string | null;
        }[]
      | null;
    integrationsTitle?: string | null;
    integrationsDescription?: string | null;
    deploymentTitle?: string | null;
    deploymentDescription?: string | null;
    deploymentOptions?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  security?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    cards?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    heading?: string | null;
    description?: string | null;
    buttons?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-page".
 */
export interface PublicHealthPage {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
    image?: string | null;
  };
  impact?: {
    heading?: string | null;
    description?: string | null;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  threeTier?: {
    heading?: string | null;
    description?: string | null;
    tiers?:
      | {
          bannerLabel: string;
          happens?:
            | {
                item: string;
                id?: string | null;
              }[]
            | null;
          dataFlows?:
            | {
                item: string;
                id?: string | null;
              }[]
            | null;
          users?:
            | {
                role: string;
                description: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  architecture?: {
    heading?: string | null;
    description?: string | null;
    classifications?:
      | {
          level: string;
          timeBadge?: string | null;
          title: string;
          description: string;
          tags?:
            | {
                tag: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    heading?: string | null;
    description?: string | null;
    buttons?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-page".
 */
export interface ResourcesPage {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
    image?: string | null;
  };
  filterTabs?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  blogsSection?: {
    heading?: string | null;
    seeAllLabel?: string | null;
    seeAllHref?: string | null;
  };
  blogListing?: {
    title?: string | null;
    metaDescription?: string | null;
    heading?: string | null;
    description?: string | null;
    backLabel?: string | null;
    backHref?: string | null;
  };
  newsletterCta?: {
    heading?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-pages".
 */
export interface UtilityPage {
  id: number;
  comingSoon?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    backLabel?: string | null;
    backHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  contactEmailCc?: T;
  calendlyUrl?: T;
  newsletterUrl?: T;
  featuredVideoUrl?: T;
  contactRoles?:
    | T
    | {
        id?: T;
        label?: T;
        description?: T;
      };
  contactForm?:
    | T
    | {
        intro?: T;
        submitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
        privacyNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
        isDark?: T;
        id?: T;
      };
  solutionsNav?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  copyrightText?: T;
  sectionLabels?:
    | T
    | {
        menuHeading?: T;
        solutionsHeading?: T;
      };
  menuLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  solutionsLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        name?: T;
        href?: T;
        platform?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactLabel?: T;
  contactHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        id?: T;
        title?: T;
        body?: T;
        cta?: T;
        href?: T;
        image?: T;
      };
  whoWeAre?:
    | T
    | {
        eyebrow?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
      };
  ecosystemChallenges?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  ecosystemGaps?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  partners?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  security?:
    | T
    | {
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  news?:
    | T
    | {
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
        labels?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  vision?:
    | T
    | {
        heading?: T;
      };
  foundations?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  leadership?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  grants?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-page_select".
 */
export interface PlatformPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  featuresSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              category?: T;
              subheading?: T;
              title?: T;
              description?: T;
              bullets?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              illustration?: T;
              id?: T;
            };
      };
  clinicalIntelligence?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        capabilities?:
          | T
          | {
              title?: T;
              description?: T;
              badge?: T;
              id?: T;
            };
      };
  longitudinalCare?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        columns?:
          | T
          | {
              title?: T;
              description?: T;
              bullets?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  infrastructure?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        integrationTags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        integrationsTitle?: T;
        integrationsDescription?: T;
        deploymentTitle?: T;
        deploymentDescription?: T;
        deploymentOptions?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  security?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-page_select".
 */
export interface PublicHealthPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  impact?:
    | T
    | {
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  threeTier?:
    | T
    | {
        heading?: T;
        description?: T;
        tiers?:
          | T
          | {
              bannerLabel?: T;
              happens?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              dataFlows?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              users?:
                | T
                | {
                    role?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  architecture?:
    | T
    | {
        heading?: T;
        description?: T;
        classifications?:
          | T
          | {
              level?: T;
              timeBadge?: T;
              title?: T;
              description?: T;
              tags?:
                | T
                | {
                    tag?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-page_select".
 */
export interface ResourcesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  filterTabs?:
    | T
    | {
        label?: T;
        id?: T;
      };
  blogsSection?:
    | T
    | {
        heading?: T;
        seeAllLabel?: T;
        seeAllHref?: T;
      };
  blogListing?:
    | T
    | {
        title?: T;
        metaDescription?: T;
        heading?: T;
        description?: T;
        backLabel?: T;
        backHref?: T;
      };
  newsletterCta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-pages_select".
 */
export interface UtilityPagesSelect<T extends boolean = true> {
  comingSoon?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        backLabel?: T;
        backHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}