/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'team-members': TeamMember;
    'grants-awards': GrantsAward;
    partners: Partner;
    'solution-pages': SolutionPage;
    'blog-posts': BlogPost;
    'featured-videos': FeaturedVideo;
    'short-videos': ShortVideo;
    'deep-dives': DeepDive;
    'external-articles': ExternalArticle;
    'legal-pages': LegalPage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'grants-awards': GrantsAwardsSelect<false> | GrantsAwardsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'solution-pages': SolutionPagesSelect<false> | SolutionPagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'featured-videos': FeaturedVideosSelect<false> | FeaturedVideosSelect<true>;
    'short-videos': ShortVideosSelect<false> | ShortVideosSelect<true>;
    'deep-dives': DeepDivesSelect<false> | DeepDivesSelect<true>;
    'external-articles': ExternalArticlesSelect<false> | ExternalArticlesSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-intro': HomeIntro;
    'home-why': HomeWhy;
    'home-scale': HomeScale;
    'home-does': HomeDoe;
    'home-platform': HomePlatform;
    'home-serve': HomeServe;
    'home-impact': HomeImpact;
    'home-insights': HomeInsight;
    'home-ahead': HomeAhead;
    'home-contact': HomeContact;
    'about-intro': AboutIntro;
    'about-problem': AboutProblem;
    'about-building': AboutBuilding;
    'about-platform': AboutPlatform;
    'about-now': AboutNow;
    'about-mission': AboutMission;
    'about-leadership': AboutLeadership;
    'about-grants': AboutGrant;
    'home-partners': HomePartner;
    'home-security': HomeSecurity;
    'about-cta': AboutCta;
    'platform-hero': PlatformHero;
    'platform-features': PlatformFeature;
    'platform-clinical-intelligence': PlatformClinicalIntelligence;
    'platform-longitudinal-care': PlatformLongitudinalCare;
    'platform-infrastructure': PlatformInfrastructure;
    'platform-security': PlatformSecurity;
    'platform-cta': PlatformCta;
    'public-health-hero': PublicHealthHero;
    'public-health-impact': PublicHealthImpact;
    'public-health-three-tier': PublicHealthThreeTier;
    'public-health-architecture': PublicHealthArchitecture;
    'public-health-cta': PublicHealthCta;
    'resources-hero': ResourcesHero;
    'resources-videos-section': ResourcesVideosSection;
    'resources-deep-dives-section': ResourcesDeepDivesSection;
    'resources-articles-section': ResourcesArticlesSection;
    'resources-blogs-section': ResourcesBlogsSection;
    'resources-blog-listing': ResourcesBlogListing;
    'resources-newsletter': ResourcesNewsletter;
    'utility-pages': UtilityPage;
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'home-intro': HomeIntroSelect<false> | HomeIntroSelect<true>;
    'home-why': HomeWhySelect<false> | HomeWhySelect<true>;
    'home-scale': HomeScaleSelect<false> | HomeScaleSelect<true>;
    'home-does': HomeDoesSelect<false> | HomeDoesSelect<true>;
    'home-platform': HomePlatformSelect<false> | HomePlatformSelect<true>;
    'home-serve': HomeServeSelect<false> | HomeServeSelect<true>;
    'home-impact': HomeImpactSelect<false> | HomeImpactSelect<true>;
    'home-insights': HomeInsightsSelect<false> | HomeInsightsSelect<true>;
    'home-ahead': HomeAheadSelect<false> | HomeAheadSelect<true>;
    'home-contact': HomeContactSelect<false> | HomeContactSelect<true>;
    'about-intro': AboutIntroSelect<false> | AboutIntroSelect<true>;
    'about-problem': AboutProblemSelect<false> | AboutProblemSelect<true>;
    'about-building': AboutBuildingSelect<false> | AboutBuildingSelect<true>;
    'about-platform': AboutPlatformSelect<false> | AboutPlatformSelect<true>;
    'about-now': AboutNowSelect<false> | AboutNowSelect<true>;
    'about-mission': AboutMissionSelect<false> | AboutMissionSelect<true>;
    'about-leadership': AboutLeadershipSelect<false> | AboutLeadershipSelect<true>;
    'about-grants': AboutGrantsSelect<false> | AboutGrantsSelect<true>;
    'home-partners': HomePartnersSelect<false> | HomePartnersSelect<true>;
    'home-security': HomeSecuritySelect<false> | HomeSecuritySelect<true>;
    'about-cta': AboutCtaSelect<false> | AboutCtaSelect<true>;
    'platform-hero': PlatformHeroSelect<false> | PlatformHeroSelect<true>;
    'platform-features': PlatformFeaturesSelect<false> | PlatformFeaturesSelect<true>;
    'platform-clinical-intelligence': PlatformClinicalIntelligenceSelect<false> | PlatformClinicalIntelligenceSelect<true>;
    'platform-longitudinal-care': PlatformLongitudinalCareSelect<false> | PlatformLongitudinalCareSelect<true>;
    'platform-infrastructure': PlatformInfrastructureSelect<false> | PlatformInfrastructureSelect<true>;
    'platform-security': PlatformSecuritySelect<false> | PlatformSecuritySelect<true>;
    'platform-cta': PlatformCtaSelect<false> | PlatformCtaSelect<true>;
    'public-health-hero': PublicHealthHeroSelect<false> | PublicHealthHeroSelect<true>;
    'public-health-impact': PublicHealthImpactSelect<false> | PublicHealthImpactSelect<true>;
    'public-health-three-tier': PublicHealthThreeTierSelect<false> | PublicHealthThreeTierSelect<true>;
    'public-health-architecture': PublicHealthArchitectureSelect<false> | PublicHealthArchitectureSelect<true>;
    'public-health-cta': PublicHealthCtaSelect<false> | PublicHealthCtaSelect<true>;
    'resources-hero': ResourcesHeroSelect<false> | ResourcesHeroSelect<true>;
    'resources-videos-section': ResourcesVideosSectionSelect<false> | ResourcesVideosSectionSelect<true>;
    'resources-deep-dives-section': ResourcesDeepDivesSectionSelect<false> | ResourcesDeepDivesSectionSelect<true>;
    'resources-articles-section': ResourcesArticlesSectionSelect<false> | ResourcesArticlesSectionSelect<true>;
    'resources-blogs-section': ResourcesBlogsSectionSelect<false> | ResourcesBlogsSectionSelect<true>;
    'resources-blog-listing': ResourcesBlogListingSelect<false> | ResourcesBlogListingSelect<true>;
    'resources-newsletter': ResourcesNewsletterSelect<false> | ResourcesNewsletterSelect<true>;
    'utility-pages': UtilityPagesSelect<false> | UtilityPagesSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The people shown in the leadership carousel on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  title: string;
  about: string;
  /**
   * Full address, starting with https://
   */
  linkedinUrl?: string | null;
  /**
   * Recommended size: 400 × 400 px or larger square crop. JPG or WebP, under 200 KB. Use a descriptive file name such as arjun-gupta.jpg, dr-rohit-sadanand.webp. Stick to lowercase letters, numbers, and hyphens.
   */
  photo?: (number | null) | Media;
  /**
   * Optional fallback static path if no upload is provided
   */
  photoUrl?: string | null;
  group?: ('team' | 'advisors') | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every image and file used on the website. Upload here first, then pick the image from the page section that needs it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility. When uploading, use a descriptive file name (e.g. hero-bg.webp, partner-birac-logo.png).
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The recognition timeline on the About page. Entries alternate left and right automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-awards".
 */
export interface GrantsAward {
  id: number;
  year: string;
  title: string;
  subtitle?: string | null;
  /**
   * Recommended size: 128 × 128 px or smaller. PNG or SVG with a transparent background. Use a descriptive file name such as grant-birac-icon.png, ecosystem-clinicians-icon.svg. Stick to lowercase letters, numbers, and hyphens.
   */
  icon?: (number | null) | Media;
  /**
   * Optional fallback static path if no upload is provided
   */
  iconUrl?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every partner logo on the site. On the About page they fill two rows, chosen by “Which row on the About page”; the ones ticked “Show on the home page” also scroll along the home page’s Impact section. Both follow “Order on the page”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Used as the image description for screen readers.
   */
  name: string;
  /**
   * Recommended size: 400 × 120 px or similar wide logo. PNG or SVG with a transparent background. Use a descriptive file name such as partner-birac-logo.png, partner-amity-logo.svg. Stick to lowercase letters, numbers, and hyphens.
   */
  logo?: (number | null) | Media;
  /**
   * Leave this empty and use the Logo upload above. It is only used for logos already built into the site, such as /new/meity.jpg, and is ignored whenever an upload is present.
   */
  logoUrl?: string | null;
  /**
   * Hospitals, universities and research bodies go in the top row; funders, incubators and programmes in the quieter row beneath.
   */
  group?: ('institution' | 'supporter') | null;
  /**
   * Adds this logo to the scrolling strip in the home page’s Impact section.
   */
  showOnHome?: boolean | null;
  /**
   * Lower numbers appear first. The current logos are numbered 10, 20, 30 and so on, so you can slot a new one in between by giving it a number like 25. New logos start at 1000, which puts them at the end of the strip.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Two pages share this layout: Hospital / Clinician / CoE (/hospital) and Life Science / Pharma (/life-science). Open the one you want to edit — do not create new entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-pages".
 */
export interface SolutionPage {
  id: number;
  slug: 'hospital' | 'pharma';
  /**
   * The top of the page. The headline is split so part of it can be coloured.
   */
  hero: {
    eyebrow?: string | null;
    titleLine1: string;
    titleHighlight: string;
    subtitle: string;
    /**
     * Used on the Hospital page. Leave empty on Life Science, which shows three cards there instead.
     */
    stats?:
      | {
          figure: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The dark carousel. One card is open at a time; the rest stay as titles beside it.
   */
  clinicalBurden: {
    label: string;
    heading: string;
    description: string;
    /**
     * Four reads best. They are numbered in this order.
     */
    cards?:
      | {
          title: string;
          /**
           * Shown when the card is the open one. Two lines reads best.
           */
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The numbered steps, each beside a picture of the product. The pictures are built into the page and are not editable here.
   */
  howItWorks: {
    label: string;
    heading: string;
    description: string;
    /**
     * Each step is paired with a fixed illustration, so adding or removing one changes which picture a step gets.
     */
    rows?:
      | {
          /**
           * One or two words for the step pills above the walkthrough, e.g. “Capture”.
           */
          stepLabel?: string | null;
          category: string;
          title: string;
          description: string;
          callout: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The dark band: a figure per column, with a before and after line.
   */
  measurableOutcomes: {
    label: string;
    heading: string;
    description: string;
    /**
     * Three fit the row.
     */
    metrics?:
      | {
          /**
           * The large line, e.g. “90%+”, “Minutes”, “Registry-ready”. Words are fine.
           */
          figure?: string | null;
          label: string;
          before?: string | null;
          after?: string | null;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional. Use it to say what the figures rest on, e.g. that they vary by centre.
     */
    footnote?: string | null;
  };
  /**
   * The heading above the enquiry form at the bottom of the page.
   */
  cta: {
    heading: string;
    description: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles. They appear on the Resources page, on the /blog listing, and can be featured in the home page news section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * The last part of the link, e.g. rare-disease-policy gives /blog/rare-disease-policy. Lowercase letters, numbers and hyphens only. Changing this breaks existing links.
   */
  slug: string;
  excerpt: string;
  author: string;
  publishedAt: string;
  /**
   * Offers this item to the home page's Insights section: one featured item (a featured video, if any is ticked) and up to four beside it. If more are ticked than fit, the ones lowest in “Order on the page” are used.
   */
  showOnHome?: boolean | null;
  /**
   * Optional. The cards on the home page are narrower than on this page, so a long title can crowd them. Leave empty to use the title above.
   */
  homeTitle?: string | null;
  featuredOnHome?: boolean | null;
  readTime: string;
  category: string;
  /**
   * A hex colour for the category label. Genetico blue is #024385; amber is #d97706.
   */
  categoryColor: string;
  /**
   * Recommended size: 800 × 450 px (16:9). JPG, WebP, or PNG, under 250 KB. Use a descriptive file name such as blog-rare-disease-policy.webp. Stick to lowercase letters, numbers, and hyphens.
   */
  thumbnailImage?: (number | null) | Media;
  /**
   * Optional fallback: CSS gradient or static image path if no upload is provided
   */
  thumbnail?: string | null;
  /**
   * Add one paragraph per row. Drag to reorder.
   */
  content: {
    paragraph: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * The large video panel near the top of the Resources page. Only the first entry is shown, so keep one here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos".
 */
export interface FeaturedVideo {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Paste the link from YouTube's Share button, e.g. https://youtu.be/abc123. Shorts and normal videos both work.
   */
  youtubeUrl: string;
  duration?: string | null;
  /**
   * For example: Case study · AIIMS Delhi · Documentary
   */
  kicker?: string | null;
  /**
   * Shown under the watch button. For example: Amar Ujala Exclusive
   */
  source?: string | null;
  articleLink?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * When this was published. Shown on the Resources page and used to order items that have one.
   */
  publishedAt?: string | null;
  /**
   * Offers this item to the home page's Insights section: one featured item (a featured video, if any is ticked) and up to four beside it. If more are ticked than fit, the ones lowest in “Order on the page” are used.
   */
  showOnHome?: boolean | null;
  /**
   * Optional. The cards on the home page are narrower than on this page, so a long title can crowd them. Leave empty to use the title above.
   */
  homeTitle?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The horizontal row of small video cards on the Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-videos".
 */
export interface ShortVideo {
  id: number;
  title: string;
  description?: string | null;
  category: string;
  /**
   * Paste the link from YouTube's Share button, e.g. https://youtu.be/abc123. Shorts and normal videos both work.
   */
  youtubeUrl: string;
  duration?: string | null;
  /**
   * When this was published. Shown on the Resources page and used to order items that have one.
   */
  publishedAt?: string | null;
  /**
   * Offers this item to the home page's Insights section: one featured item (a featured video, if any is ticked) and up to four beside it. If more are ticked than fit, the ones lowest in “Order on the page” are used.
   */
  showOnHome?: boolean | null;
  /**
   * Optional. The cards on the home page are narrower than on this page, so a long title can crowd them. Leave empty to use the title above.
   */
  homeTitle?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form video sessions on the Resources page. Each one gets a full-width panel that alternates left and right.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-dives".
 */
export interface DeepDive {
  id: number;
  title: string;
  description?: string | null;
  category: string;
  /**
   * Hex color for the category label (e.g. #d97706)
   */
  categoryColor?: string | null;
  /**
   * Paste the link from YouTube's Share button, e.g. https://youtu.be/abc123. Shorts and normal videos both work.
   */
  youtubeUrl: string;
  duration?: string | null;
  /**
   * Event or source shown on the video panel (e.g. Global Rare Disease Summit · Geneva)
   */
  sourceLabel?: string | null;
  /**
   * Optional CSS background gradient for the video panel. Leave empty to use the YouTube thumbnail.
   */
  thumbnailGradient?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Place the video on the left side. Leave unchecked to alternate automatically by sort order.
   */
  videoLeft?: boolean | null;
  /**
   * When this was published. Shown on the Resources page and used to order items that have one.
   */
  publishedAt?: string | null;
  /**
   * Offers this item to the home page's Insights section: one featured item (a featured video, if any is ticked) and up to four beside it. If more are ticked than fit, the ones lowest in “Order on the page” are used.
   */
  showOnHome?: boolean | null;
  /**
   * Optional. The cards on the home page are narrower than on this page, so a long title can crowd them. Leave empty to use the title above.
   */
  homeTitle?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Links out to articles published elsewhere (LinkedIn, press). Shown in the “Articles” section of the Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-articles".
 */
export interface ExternalArticle {
  id: number;
  title: string;
  /**
   * Full address, starting with https://
   */
  url: string;
  /**
   * When this was published. Shown on the Resources page and used to order items that have one.
   */
  publishedAt?: string | null;
  /**
   * Offers this item to the home page's Insights section: one featured item (a featured video, if any is ticked) and up to four beside it. If more are ticked than fit, the ones lowest in “Order on the page” are used.
   */
  showOnHome?: boolean | null;
  /**
   * Optional. The cards on the home page are narrower than on this page, so a long title can crowd them. Leave empty to use the title above.
   */
  homeTitle?: string | null;
  /**
   * Lower numbers appear first. Use 10, 20, 30 so you can slot items in later.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form legal pages such as the privacy policy. The web address comes from the “slug” field — privacy-policy becomes /privacy-policy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug: string;
  title: string;
  metaDescription?: string | null;
  lastUpdated: string;
  sections?:
    | {
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'grants-awards';
        value: number | GrantsAward;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'solution-pages';
        value: number | SolutionPage;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'featured-videos';
        value: number | FeaturedVideo;
      } | null)
    | ({
        relationTo: 'short-videos';
        value: number | ShortVideo;
      } | null)
    | ({
        relationTo: 'deep-dives';
        value: number | DeepDive;
      } | null)
    | ({
        relationTo: 'external-articles';
        value: number | ExternalArticle;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  about?: T;
  linkedinUrl?: T;
  photo?: T;
  photoUrl?: T;
  group?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grants-awards_select".
 */
export interface GrantsAwardsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  subtitle?: T;
  icon?: T;
  iconUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoUrl?: T;
  group?: T;
  showOnHome?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-pages_select".
 */
export interface SolutionPagesSelect<T extends boolean = true> {
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleHighlight?: T;
        subtitle?: T;
        stats?:
          | T
          | {
              figure?: T;
              label?: T;
              id?: T;
            };
      };
  clinicalBurden?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        rows?:
          | T
          | {
              stepLabel?: T;
              category?: T;
              title?: T;
              description?: T;
              callout?: T;
              id?: T;
            };
      };
  measurableOutcomes?:
    | T
    | {
        label?: T;
        heading?: T;
        description?: T;
        metrics?:
          | T
          | {
              figure?: T;
              label?: T;
              before?: T;
              after?: T;
              note?: T;
              id?: T;
            };
        footnote?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  author?: T;
  publishedAt?: T;
  showOnHome?: T;
  homeTitle?: T;
  featuredOnHome?: T;
  readTime?: T;
  category?: T;
  categoryColor?: T;
  thumbnailImage?: T;
  thumbnail?: T;
  content?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-videos_select".
 */
export interface FeaturedVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  youtubeUrl?: T;
  duration?: T;
  kicker?: T;
  source?: T;
  articleLink?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  publishedAt?: T;
  showOnHome?: T;
  homeTitle?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-videos_select".
 */
export interface ShortVideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  youtubeUrl?: T;
  duration?: T;
  publishedAt?: T;
  showOnHome?: T;
  homeTitle?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-dives_select".
 */
export interface DeepDivesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  categoryColor?: T;
  youtubeUrl?: T;
  duration?: T;
  sourceLabel?: T;
  thumbnailGradient?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  videoLeft?: T;
  publishedAt?: T;
  showOnHome?: T;
  homeTitle?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-articles_select".
 */
export interface ExternalArticlesSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  publishedAt?: T;
  showOnHome?: T;
  homeTitle?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  metaDescription?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The dark band at the very top of the home page: the headline, the introduction, the two buttons and the “Built with” strip below the product picture.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-intro".
 */
export interface HomeIntro {
  id: number;
  /**
   * The white part of the headline.
   */
  headline?: string | null;
  /**
   * Follows the headline, in light blue.
   */
  headlineAccent?: string | null;
  blurb?: string | null;
  /**
   * Scrolls to “Why Genetico exists”.
   */
  primaryCta?: {
    label?: string | null;
  };
  /**
   * Scrolls to the IndiGeneUs.AI section.
   */
  secondaryCta?: {
    label?: string | null;
  };
  shotLabel?: string | null;
  marqueeLabel?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  marquee?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 01 on the page: the five parties that each hold part of a patient's information, then the network diagram and the closing line.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-why".
 */
export interface HomeWhy {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Exactly five, in order. Each one lights up its own document in the drawing beside it: clinic note, hospital system, lab report, study spreadsheet, programme form.
   */
  parties?:
    | {
        name?: string | null;
        body?: string | null;
        /**
         * The small dashed label, e.g. “PDF reports”.
         */
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Clockwise from the top. One node is drawn for each.
   */
  network?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  closing?: string | null;
  /**
   * Follows the closing line, in blue.
   */
  closingAccent?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The photo band between section 01 and the dark “What Genetico does” section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-scale".
 */
export interface HomeScale {
  id: number;
  label?: string | null;
  /**
   * Wide photo, at least 1920 px across. Leave empty to keep the current photo.
   */
  photo?: (number | null) | Media;
  /**
   * Shown in this order. Drag to reorder.
   */
  facts?:
    | {
        /**
         * Short, e.g. “~80%”.
         */
        figure?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Where the figures come from.
   */
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 02, the dark band: the five areas Genetico works across. As a visitor scrolls, each area opens in turn and its result lights up on the record beside it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-does".
 */
export interface HomeDoe {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  areas?:
    | {
        title?: string | null;
        /**
         * Shown when the area is open.
         */
        body?: string | null;
        /**
         * The line that lights up on the record beside it.
         */
        output?: string | null;
        /**
         * The small pill at the end of that line.
         */
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 03: which name is which, then the platform's four layers. Each layer opens in turn as the visitor scrolls, beside a screen drawn for it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-platform".
 */
export interface HomePlatform {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  body?: string | null;
  /**
   * The button opens the Platform page.
   */
  ctaLabel?: string | null;
  layersLabel?: string | null;
  /**
   * Exactly four, in order — capture, decide, connect, analyse. Each is paired with its own screen.
   */
  layers?:
    | {
        title?: string | null;
        body?: string | null;
        /**
         * Shown on the right.
         */
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 04: three photo cards, one per audience, each opening its page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-serve".
 */
export interface HomeServe {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Exactly three, in this order: hospitals & clinicians, life sciences & research, public health. Each links to its own page.
   */
  doors?:
    | {
        kicker?: string | null;
        title?: string | null;
        body?: string | null;
        ctaLabel?: string | null;
        /**
         * Landscape photo, about 1200 × 800 px. Leave empty to keep the current photo.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  caption?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 05: the figures, then the strip of partner logos. The logos are the “Partner logos” ticked “Show on the home page”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-impact".
 */
export interface HomeImpact {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  figures?:
    | {
        label?: string | null;
        figure?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A last figure, counted from “Grants & awards” (About page).
   */
  awardsLabel?: string | null;
  /**
   * Follows “Since <first year>, ”.
   */
  awardsBody?: string | null;
  logosLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 06: a featured film and the latest items. What appears is chosen on the Resources page — tick “Show on the home page” on a video, article or blog post.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-insights".
 */
export interface HomeInsight {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * The button opens the Resources page.
   */
  ctaLabel?: string | null;
  /**
   * Replaces the featured film's own title on this card.
   */
  featuredTitle?: string | null;
  /**
   * Landscape photo, at least 1400 px across. Leave empty to keep the current photo.
   */
  featuredPhoto?: (number | null) | Media;
  latestLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 07, the dark band: three stages from separate solutions to connected infrastructure, drawn as a network that grows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-ahead".
 */
export interface HomeAhead {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Exactly three, in order — the diagram draws one stage for each.
   */
  stages?:
    | {
        /**
         * e.g. “01 · In use”.
         */
        tag?: string | null;
        title?: string | null;
        body?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  footnote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 08: the text beside the enquiry form. The form's audience tabs and wording are under Site-wide → Contact details & form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-contact".
 */
export interface HomeContact {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the About page: the question, the headline, two buttons and the three short facts beside them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-intro".
 */
export interface AboutIntro {
  id: number;
  eyebrow?: string | null;
  /**
   * Read as one sentence: start, highlighted words, end.
   */
  headline?: {
    before?: string | null;
    highlight?: string | null;
    after?: string | null;
  };
  blurb?: string | null;
  /**
   * Scrolls to the first section.
   */
  primaryCta?: {
    label?: string | null;
  };
  /**
   * Scrolls to Leadership.
   */
  secondaryCta?: {
    label?: string | null;
  };
  /**
   * Shown in this order. Drag to reorder.
   */
  glance?:
    | {
        label?: string | null;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 01: the problem Genetico set out to solve, three cards and a closing line.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-problem".
 */
export interface AboutProblem {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  lead?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  items?:
    | {
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  closing?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 02: the five connected areas, drawn as a chain.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-building".
 */
export interface AboutBuilding {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  aside?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  chain?:
    | {
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  footnote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 03: which of the two names is which — the company and the platform side by side — then the platform in four steps.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-platform".
 */
export interface AboutPlatform {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  lead?: string | null;
  company?: {
    label?: string | null;
    statement?: string | null;
    body?: string | null;
  };
  platform?: {
    name?: string | null;
    label?: string | null;
    statement?: string | null;
    /**
     * The link opens the Platform page.
     */
    ctaLabel?: string | null;
  };
  /**
   * Shown in this order. Drag to reorder.
   */
  steps?:
    | {
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 04: the changes that make connected rare disease infrastructure practical now.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-now".
 */
export interface AboutNow {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  aside?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  drivers?:
    | {
        /**
         * e.g. “Policy”.
         */
        label?: string | null;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 05: the mission and vision statements, then where Genetico is going.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-mission".
 */
export interface AboutMission {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  mission?: string | null;
  vision?: string | null;
  horizonsLabel?: string | null;
  horizonsHeading?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  horizons?:
    | {
        /**
         * e.g. “Now”, “Next”.
         */
        when?: string | null;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  footnote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 06: the heading above the team, and the three principles under it. The people themselves are edited in “Team members” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-leadership".
 */
export interface AboutLeadership {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  subtitle?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  beliefs?:
    | {
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 07: the heading above the recognition timeline. The entries themselves are edited in “Grants & awards” just below; their count also feeds the home page's “Backed by” figure.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-grants".
 */
export interface AboutGrant {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 08: the heading above the two rows of partner logos. The logos are edited in “Partner logos” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-partners".
 */
export interface HomePartner {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 09: the trust and compliance points.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-security".
 */
export interface HomeSecurity {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Shown in this order. Drag to reorder.
   */
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Section 10: the heading and two buttons above the enquiry form at the foot of the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-cta".
 */
export interface AboutCta {
  id: number;
  /**
   * Shown after the section number, e.g. “01 — Why Genetico exists”.
   */
  eyebrow?: string | null;
  /**
   * Keep it short: it appears in the bar that follows the page as you scroll, and in the mobile menu.
   */
  menuLabel?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * Usually one or two. The first button is the more prominent one.
   */
  buttons?:
    | {
        label: string;
        /**
         * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
         */
        href: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the Platform page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-hero".
 */
export interface PlatformHero {
  id: number;
  eyebrow?: string | null;
  title: string;
  /**
   * Set in italics at the end of the headline, e.g. “rare and genetic disease”. Leave empty for a headline in one weight.
   */
  titleEmphasis?: string | null;
  subtitle?: string | null;
  ctaLabel?: string | null;
  /**
   * A path on this site such as /#get-in-touch, or a full https:// address.
   */
  ctaHref?: string | null;
  /**
   * Recommended size: 1600 × 900 px or wider (16:9). WebP, PNG, or JPG, under 600 KB. Use a descriptive file name such as platform-hero.webp, public-health-hero.png. Stick to lowercase letters, numbers, and hyphens.
   */
  image?: (number | null) | Media;
  /**
   * Optional fallback path (e.g. /hero/hero-bg.webp) if no upload is provided
   */
  imageUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The tabbed feature walkthrough below the hero. Each feature becomes one tab, numbered automatically in the order listed here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-features".
 */
export interface PlatformFeature {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  features?:
    | {
        title: string;
        category: string;
        subheading?: string | null;
        description: string;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Recommended size: 800 × 600 px or similar. SVG, PNG, or WebP with a transparent background if needed. Use a descriptive file name such as hpo-extraction.svg, ocr-digitization.png. Stick to lowercase letters, numbers, and hyphens.
         */
        illustrationImage?: (number | null) | Media;
        /**
         * Leave empty unless a developer asked you to use a built-in image path (e.g. /platform/hpo-extraction.svg).
         */
        illustration?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The clinical decision support section, with its grid of capability cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-clinical-intelligence".
 */
export interface PlatformClinicalIntelligence {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  capabilities?:
    | {
        title: string;
        description: string;
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The patient-journey section, laid out as side-by-side columns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-longitudinal-care".
 */
export interface PlatformLongitudinalCare {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  columns?:
    | {
        title: string;
        description: string;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The integrations and deployment section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-infrastructure".
 */
export interface PlatformInfrastructure {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  integrationsTitle?: string | null;
  integrationsDescription?: string | null;
  integrationBullets?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  integrationTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  deploymentTitle?: string | null;
  deploymentDescription?: string | null;
  deploymentBullets?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  deploymentOptions?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The security cards near the bottom of the Platform page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-security".
 */
export interface PlatformSecurity {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  cards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the Platform page, above the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-cta".
 */
export interface PlatformCta {
  id: number;
  heading?: string | null;
  description?: string | null;
  /**
   * Usually one or two. The first button is the more prominent one.
   */
  buttons?:
    | {
        label: string;
        /**
         * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
         */
        href: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the Public Health page. The headline is split across two lines — see the help text on each field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-hero".
 */
export interface PublicHealthHero {
  id: number;
  /**
   * Example: Digital Backbone for
   */
  titleLine1: string;
  /**
   * The plain words at the start of the second line, before the teal words. Example: India's
   */
  titleLine2?: string | null;
  /**
   * The end of the second line, shown in teal. Example: rare disease ecosystem
   */
  titleHighlight?: string | null;
  subtitle?: string | null;
  /**
   * Recommended size: 1600 × 900 px or wider (16:9). WebP, PNG, or JPG, under 600 KB. Use a descriptive file name such as platform-hero.webp, public-health-hero.png. Stick to lowercase letters, numbers, and hyphens.
   */
  image?: (number | null) | Media;
  /**
   * Optional fallback path (e.g. /hero/hero-bg.webp) if no upload is provided
   */
  imageUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The numbered impact cards directly below the hero. Numbering is added automatically in the order you list the cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-impact".
 */
export interface PublicHealthImpact {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The three stacked tier panels that explain how the system works. List the tiers top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-three-tier".
 */
export interface PublicHealthThreeTier {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  tiers?:
    | {
        bannerLabel: string;
        /**
         * Shown on the right of the dark banner, e.g. “Tertiary level · Class C”.
         */
        levelLabel?: string | null;
        happens?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        dataFlows?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        users?:
          | {
              role: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The connected-architecture diagram below the three-tier model.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-architecture".
 */
export interface PublicHealthArchitecture {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  /**
   * The small heading that sits above the list below. Example: Data classification
   */
  classificationLabel?: string | null;
  classifications?:
    | {
        level: string;
        timeBadge?: string | null;
        title: string;
        description: string;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the Public Health page, above the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-cta".
 */
export interface PublicHealthCta {
  id: number;
  heading?: string | null;
  description?: string | null;
  /**
   * Usually one or two. The first button is the more prominent one.
   */
  buttons?:
    | {
        label: string;
        /**
         * A path on this site such as /platform or /#get-in-touch, or a full https:// address.
         */
        href: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top of the Resources page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-hero".
 */
export interface ResourcesHero {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  /**
   * Recommended size: 1600 × 900 px or wider (16:9). WebP, PNG, or JPG, under 600 KB. Use a descriptive file name such as platform-hero.webp, public-health-hero.png. Stick to lowercase letters, numbers, and hyphens.
   */
  image?: (number | null) | Media;
  /**
   * Optional fallback path (e.g. /hero/hero-bg.webp) if no upload is provided
   */
  imageUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the horizontal row of short video cards. The videos themselves are edited in “Short videos” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-videos-section".
 */
export interface ResourcesVideosSection {
  id: number;
  /**
   * A short word or two, e.g. Videos.
   */
  heading?: string | null;
  title?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the long-form video sections. The videos themselves are edited in “Deep dives” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-deep-dives-section".
 */
export interface ResourcesDeepDivesSection {
  id: number;
  /**
   * A short word or two, e.g. Deep Dives.
   */
  heading?: string | null;
  title?: string | null;
  description?: string | null;
  seeAllLabel?: string | null;
  seeAllHref?: string | null;
  subtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the list of external article links. The links themselves are edited in “External articles” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-articles-section".
 */
export interface ResourcesArticlesSection {
  id: number;
  /**
   * A short word or two, e.g. Videos.
   */
  heading?: string | null;
  title?: string | null;
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading above the blog cards at the bottom of the Resources page. The posts themselves are edited in “Blog posts” just below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blogs-section".
 */
export interface ResourcesBlogsSection {
  id: number;
  /**
   * A short word or two, e.g. Blogs.
   */
  heading?: string | null;
  title?: string | null;
  description?: string | null;
  seeAllLabel?: string | null;
  seeAllHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A separate page that lists every blog post, reached from “See all” on the Resources page. This section controls only its header — the posts come from “Blog posts”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blog-listing".
 */
export interface ResourcesBlogListing {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  description?: string | null;
  backLabel?: string | null;
  backHref?: string | null;
  /**
   * Shown in the browser tab and in Google results.
   */
  title?: string | null;
  /**
   * The grey summary line under the page title in Google results.
   */
  metaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The last band on the Resources page, above the footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-newsletter".
 */
export interface ResourcesNewsletter {
  id: number;
  heading?: string | null;
  description?: string | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A placeholder page used for links that are not live yet. Nothing links to it from the main menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-pages".
 */
export interface UtilityPage {
  id: number;
  comingSoon?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    backLabel?: string | null;
    backHref?: string | null;
    /**
     * Shown in the browser tab and in Google results.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Used across the whole website: where contact form submissions go, the booking link, and the wording of the “Get in touch” form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  /**
   * The default summary shown in Google results and link previews.
   */
  siteDescription?: string | null;
  /**
   * Where enquiries from the website’s form are sent.
   */
  contactEmail: string;
  /**
   * Optional. Also receives every enquiry.
   */
  contactEmailCc?: string | null;
  newsletterUrl?: string | null;
  featuredVideoUrl?: string | null;
  /**
   * The tabs across the top of the contact form. The chosen option is included in the email you receive.
   */
  contactRoles?:
    | {
        /**
         * Not shown on the website (e.g. clinician, investor).
         */
        id: string;
        label: string;
        description?: string | null;
      }[]
    | null;
  contactForm?: {
    intro?: string | null;
    submitLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    privacyNote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The menu bar at the top of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Shown left to right in this order.
   */
  mainNav?:
    | {
        label: string;
        /**
         * Leave empty for the Solutions dropdown.
         */
        href?: string | null;
        type?: ('link' | 'dropdown') | null;
        /**
         * Tick only if this item sits on a light background.
         */
        isDark?: boolean | null;
        id?: string | null;
      }[]
    | null;
  solutionsNav?:
    | {
        label: string;
        href: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The band at the bottom of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline: string;
  /**
   * The year is added automatically.
   */
  copyrightText?: string | null;
  sectionLabels?: {
    menuHeading?: string | null;
    solutionsHeading?: string | null;
  };
  menuLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  solutionsLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        name: string;
        href: string;
        platform: 'x' | 'linkedin' | 'youtube';
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactLabel?: string | null;
  /**
   * Leave empty to jump to the contact form on whichever page the visitor is on, falling back to the home page form on pages without one.
   */
  contactHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-intro_select".
 */
export interface HomeIntroSelect<T extends boolean = true> {
  headline?: T;
  headlineAccent?: T;
  blurb?: T;
  primaryCta?:
    | T
    | {
        label?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
      };
  shotLabel?: T;
  marqueeLabel?: T;
  marquee?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-why_select".
 */
export interface HomeWhySelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  parties?:
    | T
    | {
        name?: T;
        body?: T;
        tag?: T;
        id?: T;
      };
  network?:
    | T
    | {
        label?: T;
        id?: T;
      };
  closing?: T;
  closingAccent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-scale_select".
 */
export interface HomeScaleSelect<T extends boolean = true> {
  label?: T;
  photo?: T;
  facts?:
    | T
    | {
        figure?: T;
        label?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-does_select".
 */
export interface HomeDoesSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  areas?:
    | T
    | {
        title?: T;
        body?: T;
        output?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-platform_select".
 */
export interface HomePlatformSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  body?: T;
  ctaLabel?: T;
  layersLabel?: T;
  layers?:
    | T
    | {
        title?: T;
        body?: T;
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-serve_select".
 */
export interface HomeServeSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  doors?:
    | T
    | {
        kicker?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        photo?: T;
        id?: T;
      };
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-impact_select".
 */
export interface HomeImpactSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  figures?:
    | T
    | {
        label?: T;
        figure?: T;
        body?: T;
        id?: T;
      };
  awardsLabel?: T;
  awardsBody?: T;
  logosLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-insights_select".
 */
export interface HomeInsightsSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  ctaLabel?: T;
  featuredTitle?: T;
  featuredPhoto?: T;
  latestLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-ahead_select".
 */
export interface HomeAheadSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  stages?:
    | T
    | {
        tag?: T;
        title?: T;
        body?: T;
        caption?: T;
        id?: T;
      };
  footnote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-contact_select".
 */
export interface HomeContactSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-intro_select".
 */
export interface AboutIntroSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?:
    | T
    | {
        before?: T;
        highlight?: T;
        after?: T;
      };
  blurb?: T;
  primaryCta?:
    | T
    | {
        label?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
      };
  glance?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-problem_select".
 */
export interface AboutProblemSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  lead?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  closing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-building_select".
 */
export interface AboutBuildingSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  aside?: T;
  chain?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  footnote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-platform_select".
 */
export interface AboutPlatformSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  lead?: T;
  company?:
    | T
    | {
        label?: T;
        statement?: T;
        body?: T;
      };
  platform?:
    | T
    | {
        name?: T;
        label?: T;
        statement?: T;
        ctaLabel?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-now_select".
 */
export interface AboutNowSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  aside?: T;
  drivers?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-mission_select".
 */
export interface AboutMissionSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  mission?: T;
  vision?: T;
  horizonsLabel?: T;
  horizonsHeading?: T;
  horizons?:
    | T
    | {
        when?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  footnote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-leadership_select".
 */
export interface AboutLeadershipSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  subtitle?: T;
  beliefs?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-grants_select".
 */
export interface AboutGrantsSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-partners_select".
 */
export interface HomePartnersSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-security_select".
 */
export interface HomeSecuritySelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-cta_select".
 */
export interface AboutCtaSelect<T extends boolean = true> {
  eyebrow?: T;
  menuLabel?: T;
  heading?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-hero_select".
 */
export interface PlatformHeroSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleEmphasis?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaHref?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-features_select".
 */
export interface PlatformFeaturesSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        category?: T;
        subheading?: T;
        description?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        illustrationImage?: T;
        illustration?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-clinical-intelligence_select".
 */
export interface PlatformClinicalIntelligenceSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        badge?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-longitudinal-care_select".
 */
export interface PlatformLongitudinalCareSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-infrastructure_select".
 */
export interface PlatformInfrastructureSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  integrationsTitle?: T;
  integrationsDescription?: T;
  integrationBullets?:
    | T
    | {
        item?: T;
        id?: T;
      };
  integrationTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  deploymentTitle?: T;
  deploymentDescription?: T;
  deploymentBullets?:
    | T
    | {
        item?: T;
        id?: T;
      };
  deploymentOptions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-security_select".
 */
export interface PlatformSecuritySelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-cta_select".
 */
export interface PlatformCtaSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-hero_select".
 */
export interface PublicHealthHeroSelect<T extends boolean = true> {
  titleLine1?: T;
  titleLine2?: T;
  titleHighlight?: T;
  subtitle?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-impact_select".
 */
export interface PublicHealthImpactSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-three-tier_select".
 */
export interface PublicHealthThreeTierSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  tiers?:
    | T
    | {
        bannerLabel?: T;
        levelLabel?: T;
        happens?:
          | T
          | {
              item?: T;
              id?: T;
            };
        dataFlows?:
          | T
          | {
              item?: T;
              id?: T;
            };
        users?:
          | T
          | {
              role?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-architecture_select".
 */
export interface PublicHealthArchitectureSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  classificationLabel?: T;
  classifications?:
    | T
    | {
        level?: T;
        timeBadge?: T;
        title?: T;
        description?: T;
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-health-cta_select".
 */
export interface PublicHealthCtaSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-hero_select".
 */
export interface ResourcesHeroSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-videos-section_select".
 */
export interface ResourcesVideosSectionSelect<T extends boolean = true> {
  heading?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-deep-dives-section_select".
 */
export interface ResourcesDeepDivesSectionSelect<T extends boolean = true> {
  heading?: T;
  title?: T;
  description?: T;
  seeAllLabel?: T;
  seeAllHref?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-articles-section_select".
 */
export interface ResourcesArticlesSectionSelect<T extends boolean = true> {
  heading?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blogs-section_select".
 */
export interface ResourcesBlogsSectionSelect<T extends boolean = true> {
  heading?: T;
  title?: T;
  description?: T;
  seeAllLabel?: T;
  seeAllHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-blog-listing_select".
 */
export interface ResourcesBlogListingSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  backLabel?: T;
  backHref?: T;
  title?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-newsletter_select".
 */
export interface ResourcesNewsletterSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  buttonLabel?: T;
  buttonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-pages_select".
 */
export interface UtilityPagesSelect<T extends boolean = true> {
  comingSoon?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        backLabel?: T;
        backHref?: T;
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  contactEmailCc?: T;
  newsletterUrl?: T;
  featuredVideoUrl?: T;
  contactRoles?:
    | T
    | {
        id?: T;
        label?: T;
        description?: T;
      };
  contactForm?:
    | T
    | {
        intro?: T;
        submitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
        privacyNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
        isDark?: T;
        id?: T;
      };
  solutionsNav?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  copyrightText?: T;
  sectionLabels?:
    | T
    | {
        menuHeading?: T;
        solutionsHeading?: T;
      };
  menuLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  solutionsLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        name?: T;
        href?: T;
        platform?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactLabel?: T;
  contactHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}